spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=UTF-8&userSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zx13103521676
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
  #静态资源配置
  mvc:
    static-path-pattern: /static/**
  #thymeleaf模板引擎配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
mybatis:
    #配置实体类的包路径
    type-aliases-package: com.example.crud.entity
    #配置对应的xml路径
    mapper-locations: classpath:mapping/*.xml