server:
  port: 8881

#给微服务设置一个名字
spring:
  application:
    name: userservice
  #连接数据库
  datasource:
    url: jdbc:mysql://localhost/test1
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://10.151.18.17:8761/eureka/ #http://localhost:8761/eureka/

