spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/REDmanager?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 19011387
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB


mybatis:
  type-aliases-package: com.example.redshop.domain
  mapper-locations: classpath:mapper/*.xml

